export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Signuppatient } from './SignupPatient'
export { default as Signupclinic } from './SignupClinic'